import Providers from "@/lib/providers";
import type { Metadata } from "next";
import { Instrument_Serif, Inter } from "next/font/google";
import "./globals.css";
import Dialogs from "@/components/dialogs";
const inter = Inter({
  variable: "--font-inter",
  // subsets: ["latin"],
});

const instrument = Instrument_Serif({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: ["400"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${instrument.variable}  antialiased`}
      >
        <Providers>
          <Dialogs />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
